name: Workflow Reusable EJ2_1  #Nombre del workflow

on:
  workflow_call: #Se ejecuta al ser llamado por otro workflow
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  mensaje:
    runs-on: [self-hosted, labs-runner]
    steps:
    - name: Mensaje
      #Comprobar que la rama empiezac on "feature/"
      run: |
        echo "El nombre de la rama es $GITHUB_REF_NAME"
        if [[ $GITHUB_REF_NAME == feature/* ]]; then
          echo "La rama empieza por feature/"
          echo "Ruta de config: ${{ inputs.config-path }}"
          echo "Token recibido: ${{ secrets.token }}"
        fi