name: Workflow Triggers EJ4  #Nombre del workflow

#Se ejecuta todos los dias a las 12
on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '25 9 * * *'

jobs: #Tareas
  
  saludo: #Mandar mensaje cuando se active
    runs-on: labs-runner
    steps:
      - name: Diario
        run: echo "Scheduled job executed!"