name: Workflow Variables EJ2  #Nombre del workflow

on:
  push: #Se ejecuta al hacer push en la rama "rama1"
    branches:
      - rama1

jobs:
  variables:
    runs-on: [self-hosted, labs-runner]
    steps:
      - name: Usar secreto pesonalizado
        run: |
          echo "Javier Valladolid recomienda ${{ secrets.MY_SECRET }}"