name: Workflow Variables EJ1  #Nombre del workflow

on:
  push: #Se ejecuta al hacer push en la rama "rama1"
    branches:
      - rama1

jobs:
  script:
    runs-on: labs-runner
    steps:
    - name: Definir variables de entorno
      env:
        MI_VARIABLE_1: valor_1
        MI_VARIABLE_2: valor_2
      run: echo "Variables definidas con exito"
    - name: Comprobar las variables
      run: echo "Mis variables son $MI_VARIABLE_1 y $MI_VARIABLE_2"
        