name: Workflow Variables EJ4  #Nombre del workflow

on:
  workflow_dispatch: #Se ejecuta en una rama a elección

jobs:
  variables:
    runs-on: [self-hosted, labs-runner]
    steps:
      #Paso 1
      - name: Checkout de repo para ver los archivos que existen
        uses: actions/checkout@v3
      - name: Comprobar si existe config.json y es valido
        run: |
          if [ ! -f "config.json" ]; then
            echo "El archivo config.json no existe"
            exit 1
          fi

          if ! jq -e . "config.json" > /dev/null 2>&1; then
            echo "El archivo config.json no es valido"
            exit 1
          fi
      #Paso 2
      - name: Extraes la versión del archivo y usarlo como output
        run: |
          VERSION=$(jq -r .version "config.json")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "La versión es: $VERSION"
      #Paso 3
      - name: Comprobar en qué rama se ejecuta el workflow
        run: |
          if [ "$GITHUB_REF" == "refs/heads/main" ]; then
            echo "El workflow se ejecuta en la rama main"
            echo "Iniciando despliegue en producción"
          elif [ "$GITHUB_REF" == "refs/heads/rama1" ]; then
            echo "El workflow se ejecuta en la rama rama1"
            echo "Iniciando despliegue en develop"
          else