name: Workflow Variables EJ5  #Nombre del workflow

on:
  push: #Se ejecuta al hacer push en la rama "rama1"
    branches:
      - rama1

jobs:

  job1:
    runs-on: [self-hosted, labs-runner]
    steps:
      - name: Definir una variable, imprimirla y definir otra con ENV
        run: |
          var1=1"
          echo "El valor de var1 es $var1"
          echo "2" = var2 >> $GITHUB_ENV
      - name: Imprimir var2
        run: |
          echo "El valor de var2 es $var2"
  
  job2:
    runs-on: [self-hosted, labs-runner]
    outputs:
      var_step_output: ${{ steps.step1.outputs.var_step_output }}
    steps:
      - id: step1
        run: echo "var_step_output=valor" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "El valor de var_step_output es $var_step_output"

  job3:
    runs-on: [self-hosted, labs-runner]
    outputs:
      var3: ${{ steps.step1.outputs.var3 }}
    steps:
      - name: Imprimir el valor de "var2"
        run: |
          echo "El valor de var2 es $var2"
      - name: Definir var3 para compartir con otros jobs.
        run: echo "var3=3" >> "$GITHUB_OUTPUT"

  job4:
    runs-on: [self-hosted, labs-runner]
    needs: job3
    steps:
      - name: Imprimir el valor de "var3"
        run: |
          echo "El valor de var3 es $var3"

  job5:
    runs-on: [self-hosted, labs-runner]
    steps:
      - name: Imprimir nombre del repositorio
        run: |
          echo "El nombre del repositorio es $GITHUB_ACTION_REPOSITORY"
      - name: Imprimir nombre de la rama
        run: |
          echo "El nombre de la rama es $GITHUB_REF_NAME"
      - name: Imprimir nombre del evento que activo el workflow
        run: |
          echo "El nombre del evento que activo el workflow es $GITHUB_EVENT_NAME"	